meta_title: "FantaBaretto"
meta_description: "Fantasy Football"
meta_image: "https://res.cloudinary.com/bdavidxyz-com/image/upload/v1641473825/rails/homeimage.png"
twitter_account: "@https://twitter.com/ShinoKouda"
